name: Go test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.10'

      - name: Build
        run: GOBUILD_TAGS= make

      - name: Test
        run: GOBUILD_TAGS= make test

      - name: Test Race
        run: GOBUILD_TAGS= make test-race
